apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: test-system
  description: Testing
  tags:
    - apigateway
  links:
  - url: https://www.google.com/
    title: Beta - test Services
    icon: location
 
spec:
  owner: demo-team
  domain: logistics
